apiVersion: apps/v1
kind: Deployment
metadata:
  name: serie-service-deployment
  labels:
    app: serie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serie-service
  template:
    metadata:
      labels:
        app: serie-service
    spec:
      containers:
      - name: serie-service
        image: docker.io/ertuncefe/serie-service:v1.5
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: serie-service
spec:
  selector:
    app: serie-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: serie-service-nodeport
spec:
  type: NodePort
  selector:
    app: serie-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30038
---
apiVersion: v1
kind: Service
metadata:
  name: serie-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: serie-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080